//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type AuthUser struct {
	ID               int64 `sql:"primary_key"`
	Username         string
	Email            string
	Role             string
	Password         string
	CreatedAt        time.Time
	LastLogin        time.Time
	Attr             string
	LastSeenStrikeID int64 // 用户已确认查看的处罚 ID，0 表示全部未读
}
