//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

// 用户违规记录表
type AuthStrikeRecord struct {
	ID         int64 `sql:"primary_key"`
	UserID     int64
	OperatorID *int64
	Reason     string
	Evidence   string
	Point      int16 // 扣分点数,默认1分
	Status     int16 // 处罚状态: 0-生效中, 1-已撤销
	CreatedAt  time.Time
	Attr       string
}
