//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

// 用户违规记录表
type AuthStrikeRecord struct {
	ID         int64 `sql:"primary_key"`
	UserID     int64
	OperatorID *int64
	Reason     string
	Evidence   string
	Point      int16 // 扣分点数,默认1分
	CreatedAt  time.Time
	RevokedAt  *time.Time // 撤销时间
	RevokedBy  *int64     // 撤销操作人用户 ID
	Attr       string
}
