//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AuthSetting = newAuthSettingTable("public", "auth_setting", "")

type authSettingTable struct {
	postgres.Table

	// Columns
	Key       postgres.ColumnString
	Value     postgres.ColumnString
	UpdatedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AuthSettingTable struct {
	authSettingTable

	EXCLUDED authSettingTable
}

// AS creates new AuthSettingTable with assigned alias
func (a AuthSettingTable) AS(alias string) *AuthSettingTable {
	return newAuthSettingTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AuthSettingTable with assigned schema name
func (a AuthSettingTable) FromSchema(schemaName string) *AuthSettingTable {
	return newAuthSettingTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AuthSettingTable with assigned table prefix
func (a AuthSettingTable) WithPrefix(prefix string) *AuthSettingTable {
	return newAuthSettingTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AuthSettingTable with assigned table suffix
func (a AuthSettingTable) WithSuffix(suffix string) *AuthSettingTable {
	return newAuthSettingTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAuthSettingTable(schemaName, tableName, alias string) *AuthSettingTable {
	return &AuthSettingTable{
		authSettingTable: newAuthSettingTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newAuthSettingTableImpl("", "excluded", ""),
	}
}

func newAuthSettingTableImpl(schemaName, tableName, alias string) authSettingTable {
	var (
		KeyColumn       = postgres.StringColumn("key")
		ValueColumn     = postgres.StringColumn("value")
		UpdatedAtColumn = postgres.TimestampzColumn("updated_at")
		allColumns      = postgres.ColumnList{KeyColumn, ValueColumn, UpdatedAtColumn}
		mutableColumns  = postgres.ColumnList{ValueColumn, UpdatedAtColumn}
		defaultColumns  = postgres.ColumnList{UpdatedAtColumn}
	)

	return authSettingTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Key:       KeyColumn,
		Value:     ValueColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
