//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AuthStrikeRecord = newAuthStrikeRecordTable("public", "auth_strike_record", "")

// 用户违规记录表
type authStrikeRecordTable struct {
	postgres.Table

	// Columns
	ID         postgres.ColumnInteger
	UserID     postgres.ColumnInteger
	OperatorID postgres.ColumnInteger
	Reason     postgres.ColumnString
	Evidence   postgres.ColumnString
	Point      postgres.ColumnInteger // 扣分点数,默认1分
	Status     postgres.ColumnInteger // 处罚状态: 0-生效中, 1-已撤销
	CreatedAt  postgres.ColumnTimestampz
	Attr       postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AuthStrikeRecordTable struct {
	authStrikeRecordTable

	EXCLUDED authStrikeRecordTable
}

// AS creates new AuthStrikeRecordTable with assigned alias
func (a AuthStrikeRecordTable) AS(alias string) *AuthStrikeRecordTable {
	return newAuthStrikeRecordTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AuthStrikeRecordTable with assigned schema name
func (a AuthStrikeRecordTable) FromSchema(schemaName string) *AuthStrikeRecordTable {
	return newAuthStrikeRecordTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AuthStrikeRecordTable with assigned table prefix
func (a AuthStrikeRecordTable) WithPrefix(prefix string) *AuthStrikeRecordTable {
	return newAuthStrikeRecordTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AuthStrikeRecordTable with assigned table suffix
func (a AuthStrikeRecordTable) WithSuffix(suffix string) *AuthStrikeRecordTable {
	return newAuthStrikeRecordTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAuthStrikeRecordTable(schemaName, tableName, alias string) *AuthStrikeRecordTable {
	return &AuthStrikeRecordTable{
		authStrikeRecordTable: newAuthStrikeRecordTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newAuthStrikeRecordTableImpl("", "excluded", ""),
	}
}

func newAuthStrikeRecordTableImpl(schemaName, tableName, alias string) authStrikeRecordTable {
	var (
		IDColumn         = postgres.IntegerColumn("id")
		UserIDColumn     = postgres.IntegerColumn("user_id")
		OperatorIDColumn = postgres.IntegerColumn("operator_id")
		ReasonColumn     = postgres.StringColumn("reason")
		EvidenceColumn   = postgres.StringColumn("evidence")
		PointColumn      = postgres.IntegerColumn("point")
		StatusColumn     = postgres.IntegerColumn("status")
		CreatedAtColumn  = postgres.TimestampzColumn("created_at")
		AttrColumn       = postgres.StringColumn("attr")
		allColumns       = postgres.ColumnList{IDColumn, UserIDColumn, OperatorIDColumn, ReasonColumn, EvidenceColumn, PointColumn, StatusColumn, CreatedAtColumn, AttrColumn}
		mutableColumns   = postgres.ColumnList{UserIDColumn, OperatorIDColumn, ReasonColumn, EvidenceColumn, PointColumn, StatusColumn, CreatedAtColumn, AttrColumn}
		defaultColumns   = postgres.ColumnList{PointColumn, StatusColumn, CreatedAtColumn, AttrColumn}
	)

	return authStrikeRecordTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		UserID:     UserIDColumn,
		OperatorID: OperatorIDColumn,
		Reason:     ReasonColumn,
		Evidence:   EvidenceColumn,
		Point:      PointColumn,
		Status:     StatusColumn,
		CreatedAt:  CreatedAtColumn,
		Attr:       AttrColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
