//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AuthOtp = newAuthOtpTable("public", "auth_otp", "")

type authOtpTable struct {
	postgres.Table

	// Columns
	Email     postgres.ColumnString
	Type      postgres.ColumnString
	CodeHash  postgres.ColumnBytea
	ExpiresAt postgres.ColumnTimestampz
	CreatedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AuthOtpTable struct {
	authOtpTable

	EXCLUDED authOtpTable
}

// AS creates new AuthOtpTable with assigned alias
func (a AuthOtpTable) AS(alias string) *AuthOtpTable {
	return newAuthOtpTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AuthOtpTable with assigned schema name
func (a AuthOtpTable) FromSchema(schemaName string) *AuthOtpTable {
	return newAuthOtpTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AuthOtpTable with assigned table prefix
func (a AuthOtpTable) WithPrefix(prefix string) *AuthOtpTable {
	return newAuthOtpTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AuthOtpTable with assigned table suffix
func (a AuthOtpTable) WithSuffix(suffix string) *AuthOtpTable {
	return newAuthOtpTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAuthOtpTable(schemaName, tableName, alias string) *AuthOtpTable {
	return &AuthOtpTable{
		authOtpTable: newAuthOtpTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newAuthOtpTableImpl("", "excluded", ""),
	}
}

func newAuthOtpTableImpl(schemaName, tableName, alias string) authOtpTable {
	var (
		EmailColumn     = postgres.StringColumn("email")
		TypeColumn      = postgres.StringColumn("type")
		CodeHashColumn  = postgres.ByteaColumn("code_hash")
		ExpiresAtColumn = postgres.TimestampzColumn("expires_at")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		allColumns      = postgres.ColumnList{EmailColumn, TypeColumn, CodeHashColumn, ExpiresAtColumn, CreatedAtColumn}
		mutableColumns  = postgres.ColumnList{CodeHashColumn, ExpiresAtColumn, CreatedAtColumn}
		defaultColumns  = postgres.ColumnList{CreatedAtColumn}
	)

	return authOtpTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Email:     EmailColumn,
		Type:      TypeColumn,
		CodeHash:  CodeHashColumn,
		ExpiresAt: ExpiresAtColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
