//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	AuthEvent = AuthEvent.FromSchema(schema)
	AuthOtp = AuthOtp.FromSchema(schema)
	AuthSetting = AuthSetting.FromSchema(schema)
	AuthStrikeRecord = AuthStrikeRecord.FromSchema(schema)
	AuthUser = AuthUser.FromSchema(schema)
}
